"""
airflow_generator.py — Apache Airflow DAG Generator (Trilha 7)

Generates Apache Airflow DAGs from the canonical AST graph.

Task graph is derived directly from the pipeline execution order and node
dependency graph — no LLM inference required.

Produces:
    dag_<pipeline_name>.py   — Airflow DAG Python file

Input:  canonical-model.json (MigrationPipeline)
Output: generated-code/airflow/
"""
from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from src.shared.pipeline_ast.model.canonical import MigrationNode, MigrationPipeline, NodeType


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------

@dataclass
class AirflowArtifacts:
    """Generated Airflow artifacts for a pipeline."""
    pipeline_name: str
    dag_py: str = ""

    def save(self, output_dir: Path | str) -> dict[str, Path]:
        """Write DAG file to output_dir/airflow/."""
        base = Path(output_dir) / "airflow"
        base.mkdir(parents=True, exist_ok=True)
        written: dict[str, Path] = {}
        name = self.pipeline_name.lower().replace(" ", "_")
        if self.dag_py:
            p = base / f"dag_{name}.py"
            p.write_text(self.dag_py, encoding="utf-8")
            written["dag_py"] = p
        return written


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

class AirflowGenerator:
    """
    Generates an Apache Airflow DAG from a canonical MigrationPipeline.

    The DAG task graph is derived directly from pipeline.execution_order and
    node.metadata["depends_on"] — making it deterministic and traceable.

    Usage::

        gen = AirflowGenerator()
        artifacts = gen.generate(pipeline)
        artifacts.save(Path("outputs/generated-code"))
    """

    def generate(self, pipeline: MigrationPipeline) -> AirflowArtifacts:
        artifacts = AirflowArtifacts(pipeline_name=pipeline.pipeline_name)
        artifacts.dag_py = self._build_dag(pipeline)
        return artifacts

    # ------------------------------------------------------------------

    def _build_dag(self, pipeline: MigrationPipeline) -> str:
        dag_id = pipeline.pipeline_name.lower().replace(" ", "_").replace("-", "_")
        source = pipeline.source_platform
        target = pipeline.target_platform

        # Build task graph from nodes
        task_defs: list[str] = []
        dependency_lines: list[str] = []

        # Always include Bronze → Silver → Gold tasks
        base_tasks = [
            ("bronze_extract", "Extract raw data from source", "bronze_extract"),
            ("silver_transform", "Apply transformations", "silver_transform"),
            ("gold_load", "Load to Gold / target", "gold_load"),
        ]

        prev_task_var: str | None = None
        for task_var, description, notebook in base_tasks:
            task_defs.append(textwrap.dedent(f"""\
                {task_var} = PythonOperator(
                    task_id="{task_var}",
                    python_callable=run_notebook,
                    op_kwargs={{"notebook": "{notebook}", "pipeline": "{pipeline.pipeline_name}"}},
                    dag=dag,
                )
            """))
            if prev_task_var:
                dependency_lines.append(f"{prev_task_var} >> {task_var}")
            prev_task_var = task_var

        # Add source-specific tasks from nodes
        extra_task_defs: list[str] = []
        for node in pipeline.nodes:
            if node.node_type in (NodeType.SOURCE, NodeType.SINK):
                continue  # Already covered by bronze/gold
            task_var = f"task_{node.node_id.replace('-', '_').replace('.', '_')[:40]}"
            extra_task_defs.append(textwrap.dedent(f"""\
                {task_var} = EmptyOperator(
                    task_id="{task_var}",
                    dag=dag,
                )
            """))

        all_task_defs = "\n".join(task_defs + extra_task_defs)
        all_deps = "\n".join(dependency_lines) if dependency_lines else "# no additional dependencies"

        return textwrap.dedent(f"""\
            # dag_{dag_id}.py
            # Generated by AST Engine — Airflow Generator
            # Pipeline: {pipeline.pipeline_name}
            # Source: {source} → Target: {target}
            # DO NOT EDIT MANUALLY — regenerate from canonical-model.json
            #
            # Task graph (derived from AST execution order):
            #   bronze_extract >> silver_transform >> gold_load

            from __future__ import annotations

            from datetime import datetime, timedelta
            from typing import Any

            from airflow import DAG
            from airflow.operators.empty import EmptyOperator
            from airflow.operators.python import PythonOperator

            # ---------------------------------------------------------------------------
            # Notebook runner (override with your cluster connection)
            # ---------------------------------------------------------------------------

            def run_notebook(notebook: str, pipeline: str, **kwargs: Any) -> None:
                \"\"\"Execute a notebook or script for the given pipeline stage.\"\"\"
                import subprocess
                subprocess.run(
                    ["python", f"notebooks/{{pipeline}}/{{notebook}}.py"],
                    check=True,
                )

            # ---------------------------------------------------------------------------
            # DAG definition
            # ---------------------------------------------------------------------------

            default_args = {{
                "owner": "data-migration-factory",
                "depends_on_past": False,
                "email_on_failure": True,
                "retries": 2,
                "retry_delay": timedelta(minutes=5),
            }}

            with DAG(
                dag_id="{dag_id}",
                description="AST-generated migration DAG for {pipeline.pipeline_name} ({source} → {target})",
                schedule_interval=None,
                start_date=datetime(2024, 1, 1),
                catchup=False,
                default_args=default_args,
                tags=["ast-generated", "{source}", "{target}"],
            ) as dag:

                # ---- Tasks ----
                {textwrap.indent(all_task_defs, "    ").strip()}

                # ---- Dependencies ----
                {textwrap.indent(all_deps, "    ").strip()}
        """)
