"""
lineage_engine.py — Column-Level Lineage Engine (Trilha 4)

Derives full column-to-column lineage from a MigrationPipeline canonical model.

Produces:
    column-lineage.json   — machine-readable lineage graph
    sttm.md               — Source-to-Target Mapping markdown document

Chain tracked:
    Source Table → Source Column → Transformation → Target Column
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from src.shared.pipeline_ast.model.canonical import MigrationPipeline, MigrationTransformation


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class ColumnLineage:
    """One column-level lineage edge."""
    lineage_id: str
    source_table: str
    source_column: str
    transformation_id: str
    transformation_type: str
    expression: str
    target_table: str
    target_column: str
    confidence: float = 1.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "lineage_id": self.lineage_id,
            "source_table": self.source_table,
            "source_column": self.source_column,
            "transformation_id": self.transformation_id,
            "transformation_type": self.transformation_type,
            "expression": self.expression,
            "target_table": self.target_table,
            "target_column": self.target_column,
            "confidence": self.confidence,
        }


@dataclass
class LineageReport:
    """Full column-level lineage report for a pipeline."""
    pipeline_id: str
    pipeline_name: str
    lineage: list[ColumnLineage] = field(default_factory=list)
    unmapped_targets: list[str] = field(default_factory=list)
    unmapped_sources: list[str] = field(default_factory=list)
    coverage_pct: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "pipeline_id": self.pipeline_id,
            "pipeline_name": self.pipeline_name,
            "lineage": [ln.to_dict() for ln in self.lineage],
            "unmapped_targets": self.unmapped_targets,
            "unmapped_sources": self.unmapped_sources,
            "coverage_pct": round(self.coverage_pct, 4),
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)

    def save_json(self, path: Path | str) -> Path:
        """Write column-lineage.json."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(self.to_json(), encoding="utf-8")
        return out

    def save_sttm(self, path: Path | str) -> Path:
        """Write sttm.md — Source-to-Target Mapping document."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(self.to_sttm_md(), encoding="utf-8")
        return out

    def to_sttm_md(self) -> str:
        """Generate a Markdown STTM document from the lineage report."""
        lines: list[str] = [
            f"# Source-to-Target Mapping — {self.pipeline_name}",
            "",
            f"**Pipeline ID:** `{self.pipeline_id}`  ",
            f"**Lineage Coverage:** {self.coverage_pct * 100:.1f}%  ",
            f"**Mapped Columns:** {len(self.lineage)}  ",
            "",
            "---",
            "",
            "## Column Lineage",
            "",
            "| # | Source Table | Source Column | Transformation | Expression | Target Table | Target Column | Confidence |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for i, ln in enumerate(self.lineage, 1):
            expr = ln.expression[:60].replace("|", "\\|") if ln.expression else "—"
            conf = f"{ln.confidence:.0%}"
            lines.append(
                f"| {i} | `{ln.source_table}` | `{ln.source_column}` | "
                f"{ln.transformation_type} | `{expr}` | "
                f"`{ln.target_table}` | `{ln.target_column}` | {conf} |"
            )

        if self.unmapped_targets:
            lines += [
                "",
                "## Unmapped Target Columns",
                "",
                "| Target Column |",
                "|---|",
            ]
            for col in self.unmapped_targets:
                lines.append(f"| `{col}` |")

        if self.unmapped_sources:
            lines += [
                "",
                "## Unmapped Source Columns",
                "",
                "| Source Column |",
                "|---|",
            ]
            for col in self.unmapped_sources:
                lines.append(f"| `{col}` |")

        lines += ["", "---", "", f"*Generated by AST Lineage Engine — Data Migration Factory*"]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

class LineageEngine:
    """
    Derives column-level lineage from a MigrationPipeline.

    Usage::

        engine = LineageEngine()
        report = engine.build(pipeline)
        report.save_json(Path("outputs/column-lineage.json"))
        report.save_sttm(Path("outputs/sttm.md"))
    """

    def build(self, pipeline: MigrationPipeline) -> LineageReport:
        """Build lineage report from a canonical pipeline."""
        report = LineageReport(
            pipeline_id=pipeline.pipeline_id,
            pipeline_name=pipeline.pipeline_name,
        )

        # Collect all target columns across all target tables
        all_target_cols: set[str] = set()
        for tbl in pipeline.target_tables:
            for col in tbl.columns:
                all_target_cols.add(f"{tbl.table_name}.{col.name}")

        mapped_targets: set[str] = set()
        mapped_sources: set[str] = set()

        # Map each transformation to a lineage edge
        for i, tr in enumerate(pipeline.transformations):
            target_parts = tr.target_column.rsplit(".", 1)
            target_tbl = target_parts[0] if len(target_parts) == 2 else ""
            target_col = target_parts[1] if len(target_parts) == 2 else tr.target_column

            if not tr.source_columns:
                # Passthrough or derived with no explicit source
                report.lineage.append(ColumnLineage(
                    lineage_id=f"lin-{i+1:04d}",
                    source_table="",
                    source_column="",
                    transformation_id=tr.transformation_id,
                    transformation_type=tr.transformation_type.value,
                    expression=tr.expression,
                    target_table=target_tbl,
                    target_column=target_col,
                    confidence=tr.confidence,
                ))
                mapped_targets.add(tr.target_column)
                continue

            for src_ref in tr.source_columns:
                src_parts = src_ref.rsplit(".", 1)
                src_tbl = src_parts[0] if len(src_parts) == 2 else ""
                src_col = src_parts[1] if len(src_parts) == 2 else src_ref

                report.lineage.append(ColumnLineage(
                    lineage_id=f"lin-{i+1:04d}-{src_col[:16]}",
                    source_table=src_tbl,
                    source_column=src_col,
                    transformation_id=tr.transformation_id,
                    transformation_type=tr.transformation_type.value,
                    expression=tr.expression,
                    target_table=target_tbl,
                    target_column=target_col,
                    confidence=tr.confidence,
                ))
                mapped_sources.add(src_ref)
                mapped_targets.add(tr.target_column)

        # Unmapped targets
        report.unmapped_targets = sorted(all_target_cols - mapped_targets)

        # Unmapped sources: collect all source columns declared in source tables
        all_src_cols: set[str] = set()
        for tbl in pipeline.source_tables:
            for col in tbl.columns:
                all_src_cols.add(f"{tbl.table_name}.{col.name}")
        report.unmapped_sources = sorted(all_src_cols - mapped_sources)

        # Coverage
        total_targets = len(all_target_cols)
        report.coverage_pct = (len(mapped_targets) / total_targets) if total_targets else 1.0

        return report
